/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.ControladorCliente;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;

/**
 *
 * @author xpacheco
 */
public class VentanaCrearCliente extends javax.swing.JFrame {


     //VentanaPrincipal
    VentanaRegistroDeEntrada ventanaRegistroDeEntrada;
    
    //Controlador de Clientes
    private ControladorCliente controladorCliente;
    
    private Locale localizacion;
    private ResourceBundle mensajes;
    /**
     * Creates new form VentanaCrearCliente
     */
    public VentanaCrearCliente(VentanaRegistroDeEntrada ventanaRegistroDeEntrada, ControladorCliente controladorCliente) {
        
        initComponents();
        
         //Ventana
        this.ventanaRegistroDeEntrada = ventanaRegistroDeEntrada;
        
        //Controlador
        this.controladorCliente = controladorCliente;
    }

    
    public Locale getLocalizacion() {
        return localizacion;
    }

    public void setLocalizacion(Locale localizacion) {
        this.localizacion = localizacion;
    }

    public ResourceBundle getMensajes() {
        return mensajes;
    }

    public void setMensajes(ResourceBundle mensajes) {
        this.mensajes = mensajes;
    }
    
    public void cambiarIdioma(String idioma, String localizacion){
     Lcedula.setText(mensajes.getString("cedula"));
     Ldireccion.setText(mensajes.getString("direccion"));
     Lnombre.setText(mensajes.getString("nombre"));
    Ltelefono.setText(mensajes.getString("telefono"));
     bCancelar.setText(mensajes.getString("cancelar"));
     bRegistrar.setText(mensajes.getString("registrarCliente"));
     Ltitulo.setText(mensajes.getString("tituloVCC"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        Ltitulo = new javax.swing.JLabel();
        Lcedula = new javax.swing.JLabel();
        Lnombre = new javax.swing.JLabel();
        Ldireccion = new javax.swing.JLabel();
        Ltelefono = new javax.swing.JLabel();
        txtcedula = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        txtdireccion = new javax.swing.JTextField();
        txttelefono = new javax.swing.JTextField();
        bRegistrar = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Ltitulo.setBackground(new java.awt.Color(204, 204, 204));
        Ltitulo.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Ltitulo.setText("Ingresar nuevo Cliente");

        Lcedula.setText("Cedula:");

        Lnombre.setText("Nombre:");

        Ldireccion.setText("Direccion:");

        Ltelefono.setText("Telefono:");

        bRegistrar.setText("Registrar");
        bRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRegistrarActionPerformed(evt);
            }
        });

        bCancelar.setText("Cancelar");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(bRegistrar)
                .addGap(70, 70, 70)
                .addComponent(bCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(91, Short.MAX_VALUE)
                        .addComponent(Ltitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Ldireccion)
                            .addComponent(Lnombre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lcedula, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Ltelefono, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtdireccion, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                            .addComponent(txtnombre)
                            .addComponent(txtcedula)
                            .addComponent(txttelefono))))
                .addGap(83, 83, 83))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Ltitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lcedula)
                    .addComponent(txtcedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lnombre)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Ldireccion)
                    .addComponent(txtdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ltelefono)
                    .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bRegistrar)
                    .addComponent(bCancelar))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRegistrarActionPerformed
        
        if (txtcedula.getText().equals("") || txtnombre.getText().equals("")
                || txtdireccion.getText().equals("") || txttelefono.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Faltan datos por ingresar");
        } else {
            controladorCliente.crear(txtcedula.getText(), txtnombre.getText(), txtdireccion.getText(), txttelefono.getText());
            ventanaRegistroDeEntrada.getVentanaCrearVehiculo().setVisible(true);
            limpiar();
            this.setVisible(false);
        }
    }//GEN-LAST:event_bRegistrarActionPerformed

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        
        ventanaRegistroDeEntrada.getVentanaCrearVehiculo().setVisible(true);
        limpiar();
        this.setVisible(false);
        
    }//GEN-LAST:event_bCancelarActionPerformed

    
     public void limpiar() {
        txtcedula.setText("");
        txtdireccion.setText("");
        txtnombre.setText("");
        txttelefono.setText("");
        
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lcedula;
    private javax.swing.JLabel Ldireccion;
    private javax.swing.JLabel Lnombre;
    private javax.swing.JLabel Ltelefono;
    private javax.swing.JLabel Ltitulo;
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bRegistrar;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JTextField txtcedula;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables
}
