/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.ControladorCliente;
import ec.edu.ups.controlador.ControladorVehiculo;
import ec.edu.ups.modelo.Cliente;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;

/**
 *
 * @author linar
 */
public class VentanaCrearVehiculo extends javax.swing.JFrame {


    //VentanaPrincipal
    VentanaRegistroDeEntrada ventanaRegistroDeEntrada;
    
    //Controladores
    private ControladorCliente controladorCliente;
    private ControladorVehiculo controladorVehiculo;
    //idioma
    private Locale localizacion;
    private ResourceBundle mensajes;
    
    
    /**
     * Creates new form VentanaCrearVehiculo
     */
    public VentanaCrearVehiculo(VentanaRegistroDeEntrada ventanaRegistroDeEntrada,
            ControladorVehiculo controladorVehiculo, ControladorCliente controladorCliente) {
        
        
        initComponents();
        
        //Ventana
        this.ventanaRegistroDeEntrada = ventanaRegistroDeEntrada;

        //Controladores
        this.controladorCliente = controladorCliente;
        this.controladorVehiculo = controladorVehiculo;
    }
    
    
    
     public Locale getLocalizacion() {
        return localizacion;
    }

    public void setLocalizacion(Locale localizacion) {
        this.localizacion = localizacion;
    }

    public ResourceBundle getMensajes() {
        return mensajes;
    }

    public void setMensajes(ResourceBundle mensajes) {
        this.mensajes = mensajes;
    }
    
    public void cambiarIdioma(String idioma, String localizacion){
     Lmarca.setText(mensajes.getString("marca"));
     Lmodelo.setText(mensajes.getString("modelo"));
     Lcliente.setText(mensajes.getString("clienteVS"));
     Lplaca.setText(mensajes.getString("placa"));
     Ltitulo.setText(mensajes.getString("tituloVC"));
     btnuevo.setText(mensajes.getString("botonCrear"));
     btcancelar.setText(mensajes.getString("cancelar"));
     btregistrar.setText(mensajes.getString("registrarVehiculo"));
     txtcliente.setText(mensajes.getString("elegirCliente"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Ltitulo = new javax.swing.JLabel();
        Lplaca = new javax.swing.JLabel();
        Lmarca = new javax.swing.JLabel();
        Lmodelo = new javax.swing.JLabel();
        Lcliente = new javax.swing.JLabel();
        txtplaca = new javax.swing.JTextField();
        txtmarca = new javax.swing.JTextField();
        txtmodelo = new javax.swing.JTextField();
        btnuevo = new javax.swing.JButton();
        btregistrar = new javax.swing.JButton();
        btcancelar = new javax.swing.JButton();
        txtcliente = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Ltitulo.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Ltitulo.setText("Ingresar Vehiculo");

        Lplaca.setText("Placa");

        Lmarca.setText("Marca");

        Lmodelo.setText("Modelo");

        Lcliente.setText("Cliente");

        btnuevo.setText("Nuevo Cliente");

        btregistrar.setText("Registrar");
        btregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btregistrarActionPerformed(evt);
            }
        });

        btcancelar.setText("Cancelar");

        txtcliente.setText("Buscar cliente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lmarca, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lplaca, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Lcliente)
                                .addComponent(Lmodelo)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtmarca, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                                    .addComponent(txtplaca)
                                    .addComponent(txtmodelo))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtcliente, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(btnuevo)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(btregistrar)
                .addGap(65, 65, 65)
                .addComponent(btcancelar)
                .addGap(0, 95, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Ltitulo)
                .addGap(104, 104, 104))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(Ltitulo)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtplaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lplaca, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtmarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Lmarca, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Lmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btregistrar)
                    .addComponent(btcancelar))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btregistrarActionPerformed
         if (txtplaca.getText().equals("") || txtmarca.getText().equals("")
                || txtmodelo.getText().equals("") || txtcliente.getText().equals("Buscar Cliente")) {
            JOptionPane.showMessageDialog(this, "Faltan datos por ingresar");
            
        } else {
            Cliente cliente = controladorCliente.buscar(txtcliente.getText());
            controladorVehiculo.crear(txtplaca.getText(), txtmarca.getText(), txtmodelo.getText(), cliente);
            ventanaRegistroDeEntrada.cargarDatosCliente(cliente);
            ventanaRegistroDeEntrada.cargarDatosTablaVehiculos();
            ventanaRegistroDeEntrada.getjTextFieldPlaca().setText(txtplaca.getText());
            limpiar();
            this.setVisible(false);
        }
    }//GEN-LAST:event_btregistrarActionPerformed

    public void limpiar() {
        txtcliente.setText("Seleccione un Cliente");
        txtmarca.setText("");
        txtmodelo.setText("");
        txtplaca.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lcliente;
    private javax.swing.JLabel Lmarca;
    private javax.swing.JLabel Lmodelo;
    private javax.swing.JLabel Lplaca;
    private javax.swing.JLabel Ltitulo;
    private javax.swing.JButton btcancelar;
    private javax.swing.JButton btnuevo;
    private javax.swing.JButton btregistrar;
    private javax.swing.JTextField txtcliente;
    private javax.swing.JTextField txtmarca;
    private javax.swing.JTextField txtmodelo;
    private javax.swing.JTextField txtplaca;
    // End of variables declaration//GEN-END:variables
}
